services:
  db:
    image: mysql:8.0
    container_name: plotnest-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: plotnest
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: plotnest-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=plotnest
    depends_on:
      - db

volumes:
  mysql_data:
